### ISSUE TITLE
[BUG] Prepared spells number not accurate for Artificer class

### ISSUE THREAD

**Issue by Arkemnos** [voodoofrog/vf-5e-sheet-addons#10]
**Module Version:** v1.0.0-beta.13

**Describe the bug**
One of my player has an Artificer character.
He is level 5 with a +3 INT modifier.
According to the rules, he is supposed to prepare a number of spells equal to his INT modifer + half his level (rounded down).
He should have 3 + 5/2 = 5.5 > 5 prepared spells.
But, the modules says he is supposed to have 8 (which I assume is INT modifier + level)

**Screenshots**
![image](https://github.com/voodoofrog/vf-5e-sheet-addons/assets/117067991/e8aa707f-ce17-47a0-9baa-92194da4d3a4)

**Foundry Version:** 
Version 11 Stable - Build 315

**Game System:** 
DnD 5e - v3.0.3

**Comment by Arkemnos** [comment]
The fix works pretty well. Thank you for such a quick release. Great job. Thank you again.

**Comment by voodoofrog** [comment]
No worries. :)
