### ISSUE TITLE
Nice job ! Not working with subclasses (ex: arcane trickster) ?

### ISSUE THREAD

**Issue by yogiteck** [voodoofrog/vf-5e-sheet-addons#9]
Hi,

You did a very useful job ! I've tried to make it work with subclasses like Arcane Trickster but it's not working. I don't know if I'm doing something wrong or if it's just normal.

Thanks again for this module !

**Comment by voodoofrog** [comment]
An Arcane Trickster is a Known Spell caster, not a Prepared Spell caster. The spell handling in this module is only for spell preparation. For the same reason, it doesn't handle Bards or Sorcerers, etc.

**Comment by voodoofrog** [comment]
If I should come across any subclasses that introduce prepared casting to a class that otherwise doesn't have to prepare spells, I'll look into it. But what's in there now should handle the vast majority of cases.
